---
title: "Bayes_Rules!_Notebook"
format: html
editor: visual
---

## Chapter 2: Bayes' Rule

```{r}
library(bayesrules)
library(tidyverse)

set_theme(theme_bw(base_size = 16, base_family = "Barlow"))
```

```{r}
data(fake_news)
fake_news <- fake_news |> as_tibble()

fake_news |> 
  count(type)
```

```{r}
fake_news |> 
  summarize(n = n(), .by = c(title_has_excl, type))
```

```{r}
sim_params <- tibble(type = c("real", "fake"),
                     prior = c(0.6, 0.4))

set.seed(1234)

sims <- sample(sim_params$type, size = 10000, prob = sim_params$prior, replace = TRUE) |>
  enframe(value = "type") |> 
  mutate(data_model = case_when(
    type == "fake" ~ .2667,
    type == "real" ~ .0222
  )) |> 
  rowwise() |> 
  mutate(usage = sample(
    c("no", "yes"), size = 1, prob = c(1- data_model, data_model)
    )) |> 
  ungroup()

sims |> 
  summarize(n = n(), .by = c(usage, type))
```

```{r}
ggplot(sims) +
  aes(x = type, fill = usage) +
  geom_bar(position = "fill")
```

```{r}
data("pop_vs_soda")

pop_vs_soda |> 
  summarize(n = n(), .by = c(pop, region))
```

```{r}
chess <- c(0.2, .5, .8)
prior <- c(0.1, 0.25, 0.65)

set.seed(1234)
chess_sim <- tibble(
  pi = sample(chess, size = 10000, prob = prior, replace = TRUE) 
)|> 
  mutate(y = rbinom(n(), size = 6, prob = pi))

chess_sim |> 
  count(pi) |> 
  mutate(prop = n / sum(n))
```

```{r}
chess_sim |> 
  ggplot() +
  aes(x = y) +
  stat_count(aes(y = after_stat(prop))) +
  facet_wrap(~pi)
```

## Chapter 3: The Beta-Binomial Bayesian Model

```{r}
library(bayesrules)
library(tidyverse)
library(extraDistr)
library(brms)
library(tidybayes)
```

```{r}
ggplot() +
  geom_function(fun = ~dbeta(., 45, 55), n = 10000) +
  labs(title = "dbeta(45, 55)")
```

```{r}
model_election <- brm(
  bf(support | trials(n_in_poll) ~ 0 + Intercept),
  data = list(support = 30, n_in_poll = 50),
  family = binomial(link = "identity"),
  prior(beta(45, 55), class = b, lb = 0, ub = 1),
  iter = 5000, warmup = 1000, seed = 1234, backend = "rstan",
  cores = 8
)
```

```{r}
model_election |> 
  gather_draws(b_Intercept) |> 
  ggplot(aes(x = .value)) +
  stat_halfeye(fill = "firebrick3") +
  labs(x = "pi", title = "Posterior for Michelle's support")
```

```{r}
model_election |> 
  gather_draws(b_Intercept) |> 
  ggplot(aes(x = .value)) +
   stat_function(geom = "area", 
                fun = ~dbeta(., 45, 55), aes(fill = "Prior"), alpha = .75) +
  geom_density(aes(fill = "Posterior"), color = NA, alpha = 0.75) +
  scale_fill_manual(values = c("firebrick3", "grey37")) +
  labs(x = "pi", title = "Posterior (Red) + Prior (Gray) for Michelle's support")
```

```{r}
model_milgram <- brm(
  bf(obey | trials(participants) ~ 0 + Intercept),
  data = list(obey = 26, participants = 40),
  family = binomial(link = "identity"),
  prior(beta(1, 10), class = b, lb = 0, ub = 1),
  iter = 5000, warmup = 1000, seed = 1234,
  backend = "rstan", cores = 8
)
```

```{r}
model_milgram |> 
  gather_draws(b_Intercept) |> 
  ggplot() +
  aes(x = .value) +
  geom_density(aes(fill = "Posterior"), color = NA, alpha = .75) +
  stat_function(aes(fill = "Prior"), fun = ~dbeta(., 1, 10), 
                alpha = .75, geom = "area") +
  xlim(0, 1) +
  scale_fill_manual(values = c("firebrick3", "grey37")) +
  ggtitle("Listening to Authority: Prior (Gray) vs Posterior (Red)")
```
